### ISSUE TITLE
ResilioSync@2.6.3.1340: hash check failed

### ISSUE THREAD

**Issue by dmzh01** [kkzzhizhou/scoop-zapps#14]
Checking hash of Resilio-Sync_x64.exe ... ERROR Hash check failed!
App:         kkzzji/ResilioSync
URL:         https://download-cdn.resilio.com/stable/windows64/Resilio-Sync_x64.exe#/setup.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    c46b4c00ea7cee5168e791096834426f31fdd46e960c1a42d97a6fad3fb4ac1d
Actual:      d5b76ba9faf198e000f96246cd0b093ad53b4accb3b3fe4125de260d4577a01d

**Comment by kkzzhizhou** [comment]
已修复（Github Action网络问题）
