### ISSUE TITLE
baidunetdisk@7.7.0.5: hash check failed

### ISSUE THREAD

**Issue by bigfei** [kkzzhizhou/scoop-zapps#17]
App:         zapps/baidunetdisk
URL:         http://issuecdn.baidupcs.com/issue/netdisk/yunguanjia/BaiduNetdisk_7.7.0.5.exe#dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    e1365ba1eafdbbafd933093f793a09b5b7e0709e57fc53d5ccf386919eaa7317
Actual:      ae84e6df274e2f672bf7f3198efb0a7607f629ffd64aa251adebf6aca74b156e

**Comment by kkzzhizhou** [comment]
PS > scoop install baidunetdisk
Installing 'baidunetdisk' (7.7.2.3) [64bit]
BaiduNetdisk_7.7.2.3.exe (151.0 MB) [=========================================================================] 100%
Checking hash of BaiduNetdisk_7.7.2.3.exe ... ok.
Extracting BaiduNetdisk_7.7.2.3.exe#dl.7z ... done.
Linking ~\scoop\apps\baidunetdisk\current => ~\scoop\apps\baidunetdisk\7.7.2.3
Creating shim for 'BaiduNetdisk'.
Creating shortcut for 百度网盘 (BaiduNetdisk.exe)
Persisting users
Running post-install script...
'baidunetdisk' (7.7.2.3) was installed successfully!
PS > date

2021年9月4日 16:12:48
