### ISSUE TITLE
ContextMenuManager@2.1.0.0: hash check failed

### ISSUE THREAD

**Issue by aether17** [kkzzhizhou/scoop-zapps#2]
Checking hash of ContextMenuManager.zip ... ERROR Hash check failed!
App:         zapps/ContextMenuManager
URL:         https://github.com/BluePointLilac/ContextMenuManager/releases/download/2.1.0.0/ContextMenuManager.zip
First bytes: 50 4B 03 04 14 00 02 08
Expected:    d2c27c448a52769b4252b89b90458c97a26e3428e526eb2828423b4c408d0148
Actual:      22c243969487128d613621e92a87c496a9a285a6926669ea7ef558129a178e9d

**Comment by kkzzhizhou** [comment]
Fixed.
