### ISSUE TITLE
zerotier@1.8.4: hash check failed

### ISSUE THREAD

**Issue by Leao9203** [kkzzhizhou/scoop-zapps#23]
Download: Status Legend:
Download: (OK):download completed.
Checking hash of ZeroTier%20One.msi ... ERROR Hash check failed!
App:         zapps/zerotier
URL:         https://download.zerotier.com/dist/ZeroTier%20One.msi#/setup.msi_
First bytes: D0 CF 11 E0 A1 B1 1A E1
Expected:    656891485ff9d132616323ea5812ec4ee63440c6f10427e3b9214c648f682d0f
Actual:      b1d95da767343880f6fa12e5858f51304379b9605a6d9a4f6fbcf8588cc5d10f

**Comment by kkzzhizhou** [comment]
已修复。
