### ISSUE TITLE
TIM精简版问题

### ISSUE THREAD

**Issue by jinzhongjia** [kkzzhizhou/scoop-zapps#27]
![image](https://user-images.githubusercontent.com/41784264/148569938-aedd26a0-80d1-4000-97dd-af90b5ab0434.png)
使用scoop安装完成TIM后经常性会发生TIM卡死然后等3秒左右恢复正常，感觉像是线程阻塞了

系统环境：windows10 2021 ltsc

**Comment by IsaacWangTT** [comment]
我这安装没事，你看看是不是运行库环境等问题

**Comment by jinzhongjia** [comment]
可能是环境问题，我实际测试了一下官方正常安装TIM，结果还是出现卡死情况，最后换用QQ精简版了🤔
