### ISSUE TITLE
tim@3.3.9.22051: Decompress Error

### ISSUE THREAD

**Issue by IsaacWangTT** [kkzzhizhou/scoop-zapps#31]
Could not find 'TIM in D:\Scoop\apps\tim\3.3.9.22051\TIM_3.3.9.22051_Green'! (error 16)

**Comment by Kelfvin** [comment]
ERROR Download failed! (Error 22) HTTP response header was bad or unexpected
ERROR https://scoop-zapps.ziiyc.com/d/TIM/TIM-3.3.9.22051.7z
    referer=https://scoop-zapps.ziiyc.com/d/TIM/
    dir=D:\Applications\Scoop\cache
    out=tim#3.3.9.22051#https_scoop-zapps.ziiyc.com_d_TIM_TIM-3.3.9.22051.7z

ERROR & 'D:\Applications\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Applications\Scoop\cache\tim.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.2 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=19852 --continue --summary-interval=0 --auto-save-interval=1

**Comment by kkzzhizhou** [comment]
已修复。

**Comment by Kelfvin** [comment]
还是不对啊，刚刚更新还是爆红
