### ISSUE TITLE
TuBaTool@2022.01: Decompress error

### ISSUE THREAD

**Issue by IsaacWangTT** [kkzzhizhou/scoop-zapps#32]
Failed to extract files from D:\Scoop\apps\TuBaTool\2022.01\TuBaTool.7z.
Log file:
  D:\Scoop\apps\TuBaTool\2022.01\7zip.log

**Comment by kkzzhizhou** [comment]
> Failed to extract files from D:\Scoop\apps\TuBaTool\2022.01\TuBaTool.7z. Log file: D:\Scoop\apps\TuBaTool\2022.01\7zip.log

已修复。
