### ISSUE TITLE
hash效验问题

### ISSUE THREAD

**Issue by Weidows** [kkzzhizhou/scoop-zapps#33]
- 比如图吧工具箱的

  ```
  "autoupdate": {
      "url": "https://scoop-zapps.ziiyc.com/d/TuBaTool/TuBaTool-$version.exe#/TuBaTool.7z",
      "hash": {
          "url": "$url.sha256",
          "regex": "$sha256"
      }
  }
  ```

  检索的url为 `https://scoop-zapps.ziiyc.com/d/TuBaTool/TuBaTool-2022.01.exe#/TuBaTool.7z.sha256`

  但实际上应该是 `https://scoop-zapps.ziiyc.com/d/TuBaTool/TuBaTool-2022.01.exe.sha256`

  ![image](https://user-images.githubusercontent.com/61131704/153190468-7f03c8e3-9bd5-4cc7-8fae-10189c726296.png)

- 改成这样应该就好了

  ```
  "autoupdate": {
      "url": "https://scoop-zapps.ziiyc.com/d/TuBaTool/TuBaTool-$version.exe#/TuBaTool.7z",
      "hash": {
          "url": "$url#/TuBaTool.7z.sha256",
          "regex": "$sha256"
      }
  }
  ```

不过还有一些其他软件也存在这问题,比如VMware

**Comment by kkzzhizhou** [comment]
> * 比如图吧工具箱的
>   ```
>   "autoupdate": {
>       "url": "https://scoop-zapps.ziiyc.com/d/TuBaTool/TuBaTool-$version.exe#/TuBaTool.7z",
>       "hash": {
>           "url": "$url.sha256",
>           "regex": "$sha256"
>       }
>   }
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   检索的url为 `https://scoop-zapps.ziiyc.com/d/TuBaTool/TuBaTool-2022.01.exe#/TuBaTool.7z.sha256`
>   但实际上应该是 `https://scoop-zapps.ziiyc.com/d/TuBaTool/TuBaTool-2022.01.exe.sha256`
>   ![image](https://user-images.githubusercontent.com/61131704/153190468-7f03c8e3-9bd5-4cc7-8fae-10189c726296.png)
> * 改成这样应该就好了
>   ```
>   "autoupdate": {
>       "url": "https://scoop-zapps.ziiyc.com/d/TuBaTool/TuBaTool-$version.exe#/TuBaTool.7z",
>       "hash": {
>           "url": "$url#/TuBaTool.7z.sha256",
>           "regex": "$sha256"
>       }
>   }
>   ```
> 
> 不过还有一些其他软件也存在这问题,比如VMware

目前已经修复，应该只是hash值获取错误的问题。
