### ISSUE TITLE
Extracting TIM-3.3.9.22051.7z ... Could not find 'TIM'! (error 16)

### ISSUE THREAD

**Issue by NoPKU** [kkzzhizhou/scoop-zapps#34]
WARN  Purging previous failed installation of TIM.
Uninstalling 'TIM' ().
'TIM' was uninstalled.
Installing 'TIM' (3.3.9.22051) [64bit]
Loading TIM-3.3.9.22051.7z from cache
Checking hash of TIM-3.3.9.22051.7z ... ok.
Extracting TIM-3.3.9.22051.7z ... Could not find 'TIM'! (error 16)
At C:\Users\Panchino\scoop\apps\scoop\current\lib\core.ps1:516 char:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find 'TIM'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'TIM'! (error 16)

**Comment by kkzzhizhou** [comment]
> WARN Purging previous failed installation of TIM. Uninstalling 'TIM' (). 'TIM' was uninstalled. Installing 'TIM' (3.3.9.22051) [64bit] Loading TIM-3.3.9.22051.7z from cache Checking hash of TIM-3.3.9.22051.7z ... ok. Extracting TIM-3.3.9.22051.7z ... Could not find 'TIM'! (error 16) At C:\Users\Panchino\scoop\apps\scoop\current\lib\core.ps1:516 char:9
> 
> * ```
>       throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
>   ```
> * ```
>       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   
>   * CategoryInfo          : OperationStopped: (Could not find 'TIM'! (error 16):String) [], RuntimeException
>   * FullyQualifiedErrorId : Could not find 'TIM'! (error 16)

已修复。
