### ISSUE TITLE
UltraISO@9.7.6.3829: hash check failed

### ISSUE THREAD

**Issue by levie-vans** [kkzzhizhou/scoop-zapps#36]
App:         scoopcn/UltraISO
URL:         https://www.ultraiso.com/uiso9_pe.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    26e3139f6ac209981c0ed5fd95d4e0c43f7dd82eeddaaf3e6585cbfcb0f95ca3
Actual:      5f26ba6ce5a487a3c9ec7663143f6d661c5500d0dd593274bd4ab6e78815d236

**Comment by kkzzhizhou** [comment]
> App: scoopcn/UltraISO URL: https://www.ultraiso.com/uiso9_pe.exe First bytes: 4D 5A 50 00 02 00 00 00 Expected: 26e3139f6ac209981c0ed5fd95d4e0c43f7dd82eeddaaf3e6585cbfcb0f95ca3 Actual: 5f26ba6ce5a487a3c9ec7663143f6d661c5500d0dd593274bd4ab6e78815d236

已修复。
