### ISSUE TITLE
please help to add xshell and xftp personal

### ISSUE THREAD

**Issue by mrchang2017** [kkzzhizhou/scoop-zapps#38]
不知道你这个是否为激活版本，但是xshell7和xftp7是由personal版本的。方便的话请添加进去。

**Comment by kkzzhizhou** [comment]
> 不知道你这个是否为激活版本，但是xshell7和xftp7是由personal版本的。方便的话请添加进去。

已添加xshell7p和xftp7p

**Comment by mrchang2017** [comment]
thanks very much / 非常多谢您的付出
