### ISSUE TITLE
安装AnyTXT出错

### ISSUE THREAD

**Issue by ovmonk** [kkzzhizhou/scoop-zapps#39]
如题，添加本仓库后，输入`sudo scoop install AnyTXT`后出现报错：`Couldn't find manifest for 'autoconfirm'.`

![image](https://user-images.githubusercontent.com/17329166/167241621-2984369f-61ee-4457-a962-157ca8ab10f6.png)

**Comment by kkzzhizhou** [comment]
> 如题，添加本仓库后，输入`sudo scoop install AnyTXT`后出现报错：`Couldn't find manifest for 'autoconfirm'.`
> 
> ![image](https://user-images.githubusercontent.com/17329166/167241621-2984369f-61ee-4457-a962-157ca8ab10f6.png)

已修复该问题
