### ISSUE TITLE
能否修改下wimlib中bin的值？

### ISSUE THREAD

**Issue by OptimusPrimeme** [kkzzhizhou/scoop-zapps#4]
https://github.com/kkzzhizhou/scoop-zapps/blob/491b36161bc18242edf751b8c4c8c88f853cd71d/bucket/wimlib.json#L29-L33
我在用scoop-search遇到了问题，那边的作者说在给程序创建别名时才需要用多维数组，然后这个manifest并不需要，请问可以更正一下吗？[Scoop-search相关issue](https://github.com/shilangyu/scoop-search/issues/12)

**Comment by kkzzhizhou** [comment]
已经修复该问题。
