### ISSUE TITLE
ResilioSync@2.6.3.1340: hash check failed

### ISSUE THREAD

**Issue by sparkslyz** [kkzzhizhou/scoop-zapps#43]
Checking hash of Resilio-Sync_x64.exe ... ERROR Hash check failed!
App:         zapps/ResilioSync
URL:         https://download-cdn.resilio.com/stable/windows64/Resilio-Sync_x64.exe#/setup.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    d5b76ba9faf198e000f96246cd0b093ad53b4accb3b3fe4125de260d4577a01d
Actual:      dc9c72e709cc7a2ea74999ce3756e6f4879cd6eae50a888a1f8ca011a1d6efa3

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/kkzzhizhou/scoop-zapps/issues/new?title=ResilioSync%402.6.3.1340%3a+hash+check+failed

**Comment by kkzzhizhou** [comment]
> Checking hash of Resilio-Sync_x64.exe ... ERROR Hash check failed! App: zapps/ResilioSync URL: https://download-cdn.resilio.com/stable/windows64/Resilio-Sync_x64.exe#/setup.exe First bytes: 4D 5A 90 00 03 00 00 00 Expected: d5b76ba9faf198e000f96246cd0b093ad53b4accb3b3fe4125de260d4577a01d Actual: dc9c72e709cc7a2ea74999ce3756e6f4879cd6eae50a888a1f8ca011a1d6efa3
> 
> Please try again or create a new issue by using the following link and paste your console output: https://github.com/kkzzhizhou/scoop-zapps/issues/new?title=ResilioSync%402.6.3.1340%3a+hash+check+failed

已修复
