### ISSUE TITLE
NavicatPremium@12.0.22.0: download via aria2 failed

### ISSUE THREAD

**Issue by tianjiaoshanzai** [kkzzhizhou/scoop-zapps#52]
网络环境应该没问题，测试了这个仓库的其他好几个app下载

ERROR Download failed! (Error 22) HTTP response header was bad or unexpected
ERROR https://scoop-zapps.ziiyc.com/d/NavicatPremium/NavicatPremium-12.0.22.0.7z
    referer=https://scoop-zapps.ziiyc.com/d/NavicatPremium/
    dir=C:\Users\yxs\scoop\cache
    out=NavicatPremium#12.0.22.0#https_scoop-zapps.ziiyc.com_d_NavicatPremium_NavicatPremium-12.0.22.0.7z

ERROR & 'C:\Users\yxs\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\yxs\scoop\cache\NavicatPremium.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=455536 --continue --summary-interval=0 --auto-save-interval=1 --all-proxy='127.0.0.1:7890'

**Comment by kkzzhizhou** [comment]
我这边也不能用aria2下载，用原生的下载方式是正常的。
