### ISSUE TITLE
网易邮箱大师地址报错mailmaster

### ISSUE THREAD

**Issue by q2051839** [kkzzhizhou/scoop-zapps#53]
mailmaster
URL http://fm.dl.126.net/mailmaster/update2/mail-4.17.8.1009.exe#/mailmaster.zip is not valid

**Comment by kkzzhizhou** [comment]
![image](https://user-images.githubusercontent.com/17605703/216885420-c1812b09-c779-4448-93fe-9002b50cf9cd.png)

没发现有问题

**Comment by kkzzhizhou** [comment]
新版本4.18.1.1006可以正常下载
