### ISSUE TITLE
Xshell@6.0.0204: hash check failed

### ISSUE THREAD

**Issue by Bryan2333** [kkzzhizhou/scoop-zapps#62]
App:         kkzzhizhou_scoop-zapps/Xshell
URL:         https://scoop-zapps.ziiyc.com/d/Xshell/Xshell-6.0.0204r.exe#/setup.exe
First bytes: 7B 22 63 6F 64 65 22 3A
Expected:    ce8566f14e23697378e6037c668a602341d84f80283c64d961568762530a55d8
Actual:      7b2f1d5eaa6dae28e3b5b975edb79e7216b033a59f3088f4dd0e065d492e8c94

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/kkzzhizhou/scoop-zapps/issues/new?title=Xshell%406.0.0204%3a+hash+check+failed

Xshell校验失败

**Comment by kkzzhizhou** [comment]
已升级alist，问题应该解决了。
