### ISSUE TITLE
raidrive@2019.12.22: download via aria2 failed

### ISSUE THREAD

**Issue by SinclairLin** [kkzzhizhou/scoop-zapps#74]
ERROR Download failed! (Error 22) HTTP response header was bad or unexpected
ERROR https://scoop-zapps.ziiyc.com/d/RaiDrive/RaiDrive-2019.12.22.exe#/setup.exe
    referer=https://scoop-zapps.ziiyc.com/d/RaiDrive/RaiDrive-2019.12.22.exe#/
    dir=D:\scoop\cache
    out=raidrive#2019.12.22#https_scoop-zapps.ziiyc.com_d_RaiDrive_RaiDrive-2019.12.22.exe_setup.exe

ERROR & 'D:\scoop\apps\aria2\current\aria2c.exe' --input-file='D:\scoop\cache\raidrive.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.3 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=19472 --continue --summary-interval=0 --auto-save-interval=1

**Comment by kkzzhizhou** [comment]
No support aria2 to download.
