### ISSUE TITLE
ALiIM@9.12.12C: hash check failed

### ISSUE THREAD

**Issue by Suyu6** [kkzzhizhou/scoop-zapps#76]
![image](https://github.com/kkzzhizhou/scoop-zapps/assets/64906597/94b3f456-a1e8-4212-b412-9cb8a0e017df)

**Comment by Suyu6** [comment]
刚刚才发现之前有报告过，但是没有回复就被关闭了，请问一下怎么解决
现在最新版本是[AliIM_taobao_(10.01.03C)](https://download.alicdn.com/wangwang/AliIM_taobao_(10.01.03C).exe)
能否获得更新？

**Comment by kkzzhizhou** [comment]
已更新
