### ISSUE TITLE
wubilex@9.9.05: hash check failed

### ISSUE THREAD

**Issue by sszq** [kkzzhizhou/scoop-zapps#8]
Installing 'wubilex' (9.9.05) [64bit]
wubiLex.7z (877.9 KB) [======================================================================================] 100%
Checking hash of wubiLex.7z ... ERROR Hash check failed!
App:         zapps/wubilex
URL:         http://wubi.aardio.com/update/wubiLex.7z
First bytes: 37 7A BC AF 27 1C 00 04
Expected:    e56a0887d42949e311d9ffd0bed8929e60364b7da159fe6f5a3cf20e3fffa835
Actual:      81d79eeb0cafad21e1572e28cc4d63ff6b2c1b4fec9ae115215d621829e32cc3

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/kkzzhizhou/scoop-zapps/issues/new?title=wubilex%409.9.05%3a+hash+check+failed

**Comment by kkzzhizhou** [comment]
wubilex已经更新版本，目前hash校验正常。
