### ISSUE TITLE
ZeroTier@1.14.2: hash check failed

### ISSUE THREAD

**Issue by thathooo** [kkzzhizhou/scoop-zapps#80]
scoop update *
ZeroTier: 1.14.1 -> 1.14.2
Updating one outdated app:
Updating 'ZeroTier' (1.14.1 -> 1.14.2)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 37a729|OK  |    27MiB/s|D:/Programs/scoop/cache/ZeroTier#1.14.2#a134005.msi_
Download: Status Legend:
Download: (OK):download completed.
Checking hash of ZeroTier%20One.msi ... ERROR Hash check failed!
App:         zapps/ZeroTier
URL:         https://download.zerotier.com/dist/ZeroTier%20One.msi#/setup.msi_
First bytes: D0 CF 11 E0 A1 B1 1A E1
Expected:    3cd94e515df47a03a204a753b2fbe2382857441fa3f1e1432def14183c7a47a8
Actual:      45a7c031e4d003512d6c08710e89ba57d9e5a0aeb6af1d26326ad3c0b2a1755d

**Comment by kkzzhizhou** [comment]
已更正
